version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(message)s"

handlers:
  default:
    level: DEBUG
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: WARNING
    propagate: False

root:
  level: INFO
  handlers: [default]
  print: PRINT